### ISSUE TITLE
is this still maintained?

### ISSUE THREAD

**Issue by guyisra** [jeremyfa/yaml.js#119]
with 38 issues and 3 PRs (and bugs that I encountered, but not sure opening an issue will do anything)

If providers are needed or @jeremyfa is not free to maintain, please say so this repo can advance

thanks

**Comment by jeremyfa** [comment]
Hey @guyisra, there is not much active work on this repo indeed, that said, it is not because it is _left behind_ or _unmaintained_.

I actually use it in various projects (and some others do too). The main problem is that I don't have the manpower to review the incoming issues and PRs as soon as they get posted (btw, some PRs have been reviewed, but just can't be merged as is), and my current focus is elsewhere for now. 

I will definitely find the time to make a maintenance pass in the coming months to review the pending bugs, but I have no plans to add new features. In other words, there are a few things from Yaml 1.2 spec that are not implemented in yaml.js, and I have no plans to add them.

I will, however, fix the bugs as soon as I can free enough time to do so.

**Comment by guyisra** [comment]
thanks for your response. If more maintainers can help you sift through the issues that would be great
