### ISSUE TITLE
Parser fails HALF the tests from https://github.com/connec/yaml-spec

### ISSUE THREAD

**Issue by ExplodingCabbage** [jeremyfa/yaml.js#31]
Below is some hacked-together code to run this parser against the tests. 59 tests pass, 45 fail because the library parses but gets the wrong result, and 11 fail because the library throws an error.

That's a pretty dire failure rate. By contrast, [`yaml-js`](https://www.npmjs.com/package/yaml-js), which seems to have half this library's popularity in terms of downloads per month, passes all the tests.

I'm not very familiar with YAML; am I missing anything in my analysis here? Is there any reason for this library to continue existing given the extent to which it fails to meet spec (and `yaml-js` does)? If not, would it be reasonable to pull it from GitHub and npm so that traffic can go to `yaml-js` instead?

``` js
var https = require('https'),
    YAML = require('yamljs');

function runTests (tests) {
    for (key in tests) {
        var testSuite = tests[key];
        for (key in testSuite) {
            var test = testSuite[key];
            try {
                if (JSON.stringify(YAML.parse(test['yaml'])) != JSON.stringify(test['result'])) {
                    console.log('FAIL', test);
                }
                else {
                    console.log('PASS', test);
                }
            }
            catch (e) {
                console.log('EXCEPTION', test);
            }
        }
    }
}

var request = require("request")
var url = "https://raw.githubusercontent.com/connec/yaml-spec/master/spec.json";

request({
    url: url,
    json: true
}, function (error, response, body) {
    runTests(body);
})
```

**Comment by jeremyfa** [comment]
Thanks for the feedback.

If you want to know which part of the YAML spec is handled by yaml.js, you can check its own spec file: https://github.com/jeremyfa/yaml.js/blob/develop/test/spec/YamlSpec.coffee

It was never planned to make yaml.js handle 100% of the YAML specs. Some of the specs may also depend on the implementation (like dates, binary, number formatting). The main goal of yaml.js is to handle most of the commonly used features of YAML, not all.

And no, it would not be reasonable at all to redirect users to use another library, especially one that has only 15 stars on github (the one you posted on your issue). yaml.js is suiting the need of many projects running in production and there is no reason to force them to use another library.

If you are not happy with this library, you can always use another one, even though in that case, I would rather use https://github.com/nodeca/js-yaml which provides excellent performances and spec implementation than the one you talk about.

Thank you for you undersanding.

**Comment by minj** [comment]
Some additional context: I was considering using yaml in a javascript project back in July, 2012.
https://github.com/nodeca/js-yaml worked but I was not happy about performance at all: an exemplary file  (~40K) took 300ms to parse in gchrome on my machine. 

Then I've found https://bitbucket.org/jeremyfa/yaml.js that was 3x quicker. The whole project started as a reimplementation of Symfony's yaml parser (more or less line for line from PHP). yaml.js was behind, however, so I forked it to fix some bugs, implement all the differences and add unit tests. It's a shame those commits were 'lost' when the repo moved to github.

All yaml samples from the [yaml spec v1.2](http://yaml.org/spec/1.2/spec.html) passed the unit tests except those dealing with multiple documents per stream. Symfony devs had apparently decided they don't them and I can't blame them.

I don't remember if I had tested https://github.com/connec/yaml-js back in the day though. In any case, a lot of time passed and this lib seems to have been rewritten last year so I can't say anything about the current situation. Therefore, when dealing with your own projects you must evaluate how much compliance you need and weigh that against the performance requirements.

**Comment by jeremyfa** [comment]
@minj Indeed, all the additional commits from bitbucket were lost when moving to GitHub. It is a shame and was a mistake. If I were doing the same today, I would convert the mercurial repository to git, merge it to the one on GitHub (which was already different than the one on bitbucket) and keep the history. In the commit adding your changes, there is a link to your bitbucket fork. Well, I would not do it that way today.

Last year's reimplementation of yaml.js improved performances and allowed to handle a few more cases (like unindented sequences). Previous specs should still work, and existing tests from the previous version have been ported to the new version.

However I believe the current version of https://github.com/nodeca/js-yaml is much better than the one back in July, 2012. It is now much faster than yaml.js (mainly because it started as a PyYAML port that they made a full rewrite, not based on regular expressions) and probably handles a wider scope of YAML specs.

Nevertheless, yaml.js implementation is still quite close to the Symfony Yaml Component implementation and I don't plan to add any significant feature in the near future. If I wanted to improve it, I would probably follow the same path as js-yaml and avoid using regular expressions. But then better directly use js-yaml.
