### ISSUE TITLE
quote control

### ISSUE THREAD

**Issue by mmumshad** [jeremyfa/yaml.js#70]
Have a quick question, I expect output to be like this:

```

---

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'
```

but I get output like this:

```

---
-
    include: RedHat.yml
    when: 'ansible_os_family == ''RedHat'''
```

Is it possible?

First, everything under "when" is encapsulated in quotes. Can I get rid of this quote?
Second, the line break between "-" and "include".

**Comment by jeremyfa** [comment]
The current rule is that if the string contains quotes, it will be escaped in order to prevent any confusion. It may be an option to use double quotes when needed if the value only have simple quotes, but not using quotes at all may lead to invalid yaml.

As for the line break, it's true that it would be better without, but then comes the question of the indentation level. If we dump with 4 spaces as indents, why would we dump:

```
- foo: bar
  some: value
```

which only indent the mapping by 2 spaces (after the first ligne beginning the sequence entry).
Or we would want to apply 4 spaces indentation there as well?

```
-   foo: bar
    some: value
```

Anyway, it's actually trickier than it looks and the current output is valid, so I'm not sure it's worth the efforts to change anything there for now.

**Comment by mmumshad** [comment]
@jeremyfa  Thank you!
